### ISSUE TITLE
lint context error and shortcut should be for expand to bracket

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#248]
When I install MarkdownEditing, my ctrl+shift+m no longer works for expand_selection to brackets. I see that it is overridden for a lint context, but that only produces an error anyway. I don't use the linter, so I don't know if this is appropriate or not?

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "lint in /home/reagle/.config/sublime-text-3/Installed Packages/MarkdownEditing.sublime-package", line 652, in run
  File "lint in /home/reagle/.config/sublime-text-3/Installed Packages/MarkdownEditing.sublime-package", line 678, in test
  File "lint in /home/reagle/.config/sublime-text-3/Installed Packages/MarkdownEditing.sublime-package", line 554, in test
IndexError: string index out of range
```

**Comment by felixhao28** [comment]
I have been considering removing shortcut for linting since it is not an often used function for most people.

The error is certainly a bug in linter, can you provide a case so that I can reproduce the bug?
