### ISSUE TITLE
UnboundLocalError: local variable 'source' referenced before assignment

### ISSUE THREAD

**Issue by helloyan** [SublimeText-Markdown/MarkdownEditing#328]
I pull the newest code,and when st3(V.3107) start，the error log below will show in the console，disable MDE it will appear

Traceback (most recent call last):
  File "D:\PortableProgram\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\PortableProgram\Sublime Text 3\sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
UnboundLocalError: local variable 'source' referenced before assignment

**Comment by helloyan** [comment]
remove and reinstall it,it's ok now
