### ISSUE TITLE
MarkdownEditing Lint not working

### ISSUE THREAD

**Issue by GitDAS** [SublimeText-Markdown/MarkdownEditing#487]
When issuing the MarkdownEditing: Markdown Lint command from the command pallete nothing happens.

The following errors are logged to the console:

```
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 999, in run_
    return self.run(edit)
  File "lint in C:\Users\DAScott\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownEditing.sublime-package", line 674, in run
  File "lint in C:\Users\DAScott\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownEditing.sublime-package", line 700, in test
  File "lint in C:\Users\DAScott\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownEditing.sublime-package", line 325, in test
  File "lint in C:\Users\DAScott\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownEditing.sublime-package", line 315, in spacecheck
TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'
```

Linting used to work previously.

Thank you

**Comment by GitDAS** [comment]
Through trial and error I found that if the mde.lint {} setting is present in the MultiMarkdown.sublime-settings file, it MUST contain the following settings (even though they exactly match the default setting in some cases) or linting will fail.

	"mde.lint":{
		"disable": ["md003","md013"], // do not remove
		"md007": 0, // do not remove
		"md026": ".,;:!", // do not remove
		"md030": {
			"ul_single": 1,
			"ol_single": 1,
			"ul_multi": 1,
			"ol_multi": 1
		} // do not remove
	},
I imagine the issue is that when parsing the settings, these values get wiped out and are not reset unless they are provided a value in the settings file.

**Comment by felixhao28** [comment]
Closing it as it's resolved
