### ISSUE TITLE
Can not configure linter rules

### ISSUE THREAD

**Issue by derwok** [SublimeText-Markdown/MarkdownEditing#551]
Linting on a MultiMarkDown file works so far.
Now I want to suppress some rules.

So I put this into my `User\MultiMarkdown.sublime-settings`

```json
    "mde.lint":{
        "disable": ["md013", "md025"],
    }
``` 

If I run the "MarkDownEditing: MarkDown Lint" command
* No output is shown
* The console shows this error:
```
Traceback (most recent call last):
  File "D:\Scratch\Pro\Sublime Text 3\sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "D:\Scratch\Pro\Sublime Text 3\Data\Installed Packages\MarkdownEditing.sublime-package\lint.py", line 676, in run
  File "D:\Scratch\Pro\Sublime Text 3\Data\Installed Packages\MarkdownEditing.sublime-package\lint.py", line 702, in test
  File "D:\Scratch\Pro\Sublime Text 3\Data\Installed Packages\MarkdownEditing.sublime-package\lint.py", line 548, in test
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by deathaxe** [comment]
ST's settings API merges settings for top-level items only. You'd need to copy over the whole dictionary from default file and modify desired settings then. You literly removed all defaults.
