### ISSUE TITLE
On Windows, cannot use any wiki-type commands

### ISSUE THREAD

**Issue by adrienne** [SublimeText-Markdown/MarkdownEditing#610]
Console output when trying to use any Wiki commands (Open Wiki page, Open Wiki Home Page, Open Today's Journal) is the following:

```
Running OpenHomePageCommand
Open page: HomePage
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\Lib\python33\sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "C:\Users\Adrienne\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownEditing.sublime-package\open_home_page.py", line 22, in run
  File "C:\Users\Adrienne\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownEditing.sublime-package\wiki_page.py", line 31, in select_page
  File "C:\Users\Adrienne\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownEditing.sublime-package\wiki_page.py", line 45, in find_files_with_name
  File "./python3.3/ntpath.py", line 256, in dirname
  File "./python3.3/ntpath.py", line 220, in split
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

```
Running OpenJournalCommand
Open page: 2021-05-26
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\Lib\python33\sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "C:\Users\Adrienne\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownEditing.sublime-package\open_journal.py", line 25, in run
  File "C:\Users\Adrienne\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownEditing.sublime-package\wiki_page.py", line 31, in select_page
  File "C:\Users\Adrienne\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownEditing.sublime-package\wiki_page.py", line 45, in find_files_with_name
  File "./python3.3/ntpath.py", line 256, in dirname
  File "./python3.3/ntpath.py", line 220, in split
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

ST version is **Stable Channel, Build 4107**

**Comment by adrienne** [comment]
Never mind, this was user error (and unclear documentation).
