### ISSUE TITLE
Error throws on streaming into view

### ISSUE THREAD

**Issue by yaroslavyaroslav** [SublimeText-Markdown/MarkdownEditing#776]
Hey, I'm using this package with my OpenAI plugin which streams text into md view. Occasionally I got spammed in logs with this error on streaming:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 954, in on_modified
    run_view_callbacks('on_modified', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 747, in run_view_callbacks
    callback(*args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "/Users/yar/Library/Application Support/Sublime Text/Installed Packages/MarkdownEditing.sublime-package/plugins/view.py", line 105, in on_modified
    pt = sel[0].begin()
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime.py", line 2291, in __getitem__
    raise IndexError()
IndexError
```

**Comment by deathaxe** [comment]
Well, something seems to delete carets. This shouldn't happen.
